# -*- coding: utf-8 -*-
"""Pico Web.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ohn7AwRSnyCIS-WZa23Q9BcvBOcqmHkL
"""

# Conjunto de dados necessários para a realização da atividade
# Necessário rodar antes de tudo

import pandas as pd
from io import StringIO

dados_texto = """
ID;Duration;Date;Pulse;Maxpulse;Calories
0;60;'2020/12/01';110;130;4091
1;60;'2020/12/02';117;145;4790
2;60;'2020/12/03';103;135;3400
3;45;'2020/12/04';109;175;2824
4;45;'2020/12/05';117;148;4060
5;60;'2020/12/06';102;127;3000
6;60;'2020/12/07';110;136;3740
7;450;'2020/12/08';104;134;2533
8;30;'2020/12/09';109;133;1951
9;60;'2020/12/10';98;124;2690
10;60;'2020/12/11';103;147;3293
11;60;'2020/12/12';100;120;2507
12;60;'2020/12/12';100;120;2507
13;60;'2020/12/13';106;128;3453
14;60;'2020/12/14';104;132;3793
15;60;'2020/12/15';98;123;2750
16;60;'2020/12/16';98;120;2152
17;60;'2020/12/17';100;120;3000
18;45;'2020/12/18';90;112;NaN
19;60;'2020/12/19';103;123;3230
20;45;'2020/12/20';97;125;2430
21;60;'2020/12/21';108;131;3642
22;45;NaN;100;119;2820
23;60;'2020/12/23';130;101;3000
24;45;'2020/12/24';105;132;2460
25;60;'2020/12/25';102;126;3345
26;60;20201226;100;120;2500
27;60;'2020/12/27';92;118;2410
28;60;'2020/12/28';103;132;NaN
29;60;'2020/12/29';100;132;2800
30;60;'2020/12/30';102;129;3803
31;60;'2020/12/31';92;115;2430
"""

df = pd.read_csv(StringIO(dados_texto), sep=";")

print(df)

df.to_csv("pico_web.csv", sep=";", index=False)

print("Arquivos salvos com sucesso!")

#Microatividade 1
import pandas as pd

dados = pd.read_csv(
    "pico_web.csv",
    sep=";",
    engine="python",
    encoding="utf-8"
)


print(dados)

#Microatividade 2
subconjunto = dados [['Pulse','Maxpulse','Calories']]
print(subconjunto)

#Microatividade 3
pd.set_option("display.max_rows", 9999)

print(dados.to_string())

#Microatividade 4
print(dados.head(10))

#Microatividade 4
print(dados.tail(10))

#Microatividade 5
print(dados.info())

#Trabalho prático

import numpy as np


dados = pd.read_csv(
    "pico_web.csv",
    sep=";",
    engine="python",
    encoding="utf-8"
)

print("\n[1] Informações gerais:")
print(dados.info())

print("\n[2] Primeiras 5 linhas:")
print(dados.head())

print("\n[3] Últimas 5 linhas:")
print(dados.tail())


dados_tratados = dados.copy()


dados_tratados["Date"] = dados_tratados["Date"].astype(str).str.replace("'", "", regex=False)


dados_tratados["Calories"] = dados_tratados["Calories"].fillna(0)

print("\n[4] Após preencher Calories nulos com 0:")
print(dados_tratados)


dados_tratados["Date"] = dados_tratados["Date"].replace("nan", "1900/01/01")

print("\n[5] Após substituir datas nulas por '1900/01/01':")
print(dados_tratados)


dados_tratados["Date"] = dados_tratados["Date"].replace("1900/01/01", np.nan)


dados_tratados["Date"] = dados_tratados["Date"].replace("20201226", "2020/12/26")

print("\n[6] Após corrigir '20201226' para '2020/12/26':")
print(dados_tratados["Date"])

dados_tratados["Date"] = pd.to_datetime(
    dados_tratados["Date"],
    format="%Y/%m/%d",
    errors="coerce"
)

print("\n[7] Após converter coluna Date para datetime:")
print(dados_tratados)


dados_tratados = dados_tratados.dropna(subset=["Date"])

print("\n[8] DATAFRAME FINAL após remover linha com Date nulo:")
print(dados_tratados)
print(f"\nTotal de linhas no dataset final: {len(dados_tratados)}")